backend:
  name: github
  repo: zorfling/chris-colborne-gatsby

media_folder: content/assets
public_folder: ../assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: attribution, label: Attribution }
      - { name: description, label: Description }
      - { name: status, label: Status, widget: 'select', options: ['DRAFT', 'PUBLISHED'] }
      - { name: featuredImage, label: 'Featured Image', widget: 'image' }
      - { name: body, label: Body, widget: markdown }
