backend:
  name: github
  repo: zorfling/chris-colborne-gatsby

media_folder: content/assets
public_folder: ../assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    folder: content/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: '{{slug}}/index'
    summary: '{{title}} -- {{year}}-{{month}}-{{day}}'
    media_folder: ''
    public_folder: ''
    extension: mdx
    view_filters:
      - label: Drafts
        field: status
        pattern: DRAFT
      - label: Published
        field: status
        pattern: PUBLISHED
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    format: frontmatter
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - {
          name: date,
          label: Date,
          widget: datetime,
          dateFormat: YYYY-MM-DD,
          timeFormat: false,
          pickerUtc: true,
        }
      - { name: attribution, label: Attribution }
      - { name: description, label: Description }
      - {
          name: status,
          label: Status,
          widget: 'select',
          options: ['DRAFT', 'PUBLISHED'],
        }
      - { name: featuredImage, label: 'Featured Image', widget: 'image' }
      - { name: body, label: Body, widget: markdown }
